// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Url struct {
	ID        string
	Original  string
	Shortened string
	Clicks    int64
	Created   time.Time
}
